Repository Team-1280/eeXiv, pull requests merged in 2024-03, with the labels that each got.

#35 chore: update code owners
  .github/CODEOWNERS
Labels: documentation, expansion, maint

#36 fix(security): potential arbitary code execution vulnerability
  .codeclimate.yml
  package-lock.json
  package.json
  scripts/run.sh
  scripts/zenodo.ts
Labels: bug, enhancement, Review effort [1-5]: 2, configuration changes, bug_fix

#38 docs(rev): upload eexiv-white-paper v3
  public/download/eexiv-white-paper/file3.pdf
  src/app/db/data.ts
Labels: documentation, Review effort [1-5]: 1

#40 chore: add deepcode ignore comment for IndirectCommandInjection in execSync call
  scripts/zenodo.ts
Labels: enhancement, refactor, Review effort [1-5]: 1

#42 ci(dependabot): configure
  .github/dependabot.yml
Labels: enhancement, expansion, ci/cd, Review effort [1-5]: 1

#49 fix(ci): dependabot commit message
  .github/dependabot.yml
Labels: enhancement, invalid, ci/cd, Review effort [1-5]: 1, dependencies

#41 [Snyk] Upgrade @tanstack/react-query from 5.20.2 to 5.20.5
  package-lock.json
  package.json
Labels: enhancement, Review effort [1-5]: 1

#50 fix(security): incorrect url substring sanitization
  src/app/components/DataDisplay.tsx
Labels: bug, enhancement, Review effort [1-5]: 1

#55 Add pendulum lab paper
  public/download/pendulum-lab/file1.pdf
  src/app/db/data.ts
Labels: documentation, enhancement
