Repository Team-1280/eeXiv, pull requests merged in 2024-02, with the labels that each got.

#4 Switch to Million.js
  package-lock.json
  package.json
Labels: enhancement, perf

#5 The better documents mega PR
  .github/workflows/style.yml
  .prettierignore
  package-lock.json
  src/app/about/page.tsx
  src/app/author/[author]/AuthorDisplay.tsx
  src/app/components/News.tsx
  src/app/db/data.ts
  src/app/db/loaders.ts
  src/app/db/workers/authorLoader.worker.ts
  src/app/document/page.tsx
  src/app/document/view/[slug]/DocumentViewer.tsx
  src/app/document/view/[slug]/VersionChooser.tsx
  src/app/document/view/[slug]/loading.module.css
  src/app/document/view/[slug]/page.tsx
  src/app/globals.css
  src/app/help/accessibility/page.tsx
  src/app/legal/copyright/page.tsx
  src/app/legal/privacy/page.tsx
  src/app/status/notifications/page.tsx
  src/app/status/page.tsx
  src/app/subscribe/page.tsx
  src/app/utils/epoch2datestring.ts
Labels: documentation, enhancement

#16 feat: add DocumentCardWrapper component to display document cards on the Documents page
  src/app/document/page.tsx
Labels: enhancement

#15 feat: add author list page
  src/app/author/page.tsx
Labels: enhancement

#12 docs: fix readme typos and update with new info
  README.md
Labels: documentation

#13 chore: update styling and add link to affiliation page
  src/app/affiliation/page.tsx
  src/app/page.tsx
Labels: enhancement

#24 chore: update CODEOWNERS file with new owners for specific directories
  .github/CODEOWNERS
Labels: documentation, enhancement

#21 feat: sort authors by the number of documents they have and update rendering of author cards accordingly
  src/app/author/page.tsx
Labels: expansion

#22 feat: sort documents by latest date on the Page component
  src/app/document/page.tsx
Labels: enhancement

#23 feat: add topic cards to display topics on the page
  src/app/topic/page.tsx
Labels: enhancement, expansion

#27 chore: add news announcement for eeXiv v2
  src/app/components/News.tsx
Labels: maint

#28 feat: add no ai badge to readme
  README.md
Labels: documentation, enhancement, jank

#29 style: adjust margins and heights in News component
  src/app/components/News.tsx
  src/app/page.tsx
Labels: style
